import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  Index,
} from 'typeorm';

export enum OperationTypeEnum {
  PAYMENT_INITIATION = 'payment.initiation',
  PAYMENT_VERIFICATION = 'payment.verification',
  REFUND_CREATION = 'refund.creation',
  SETTLEMENT_TRIGGER = 'settlement.trigger',
  WEBHOOK_PROCESSING = 'webhook.processing',
  PAYOUT_CREATION = 'payout.creation',
}

export enum IdempotencyStatusEnum {
  PROCESSING = 'processing',
  SUCCESS = 'success',
  FAILED = 'failed',
}

/**
 * Idempotency Key Entity
 *
 * Prevents duplicate execution of critical payment operations.
 * Implements the idempotency pattern:
 *
 * 1. Request comes with idempotency key + payload
 * 2. Check if key exists:
 *    - If exists with same payload → return cached response
 *    - If exists with different payload → reject with error
 *    - If not exists → process operation
 * 3. Store result with status + response
 * 4. Auto-cleanup after 24 hours (configurable)
 *
 * Supports these operations:
 * - Payment initiation (prevent double-charging)
 * - Payment verification (prevent re-verification)
 * - Refund creation (prevent duplicate refunds)
 * - Settlement trigger (prevent duplicate payables)
 * - Webhook processing (prevent reprocessing same webhook)
 * - Payout creation (prevent duplicate payouts)
 *
 * @entity idempotency_keys
 */
@Entity('idempotency_keys')
@Index(['idempotency_key'], { unique: true, where: 'status IS NOT NULL' })
@Index(['operation_type', 'expires_at'])
@Index(['status', 'created_at'])
export class IdempotencyKey {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * Unique idempotency key (generated by client or derived from request)
   * Pattern: `{tenant_id}:{user_id}:{operation}:{hash}`
   * Example: `tenant-123:user-456:payment.initiation:sha256abc...`
   */
  @Column({
    type: 'varchar',
    length: 255,
    unique: true,
  })
  idempotency_key: string;

  /**
   * Type of operation this key protects
   */
  @Column({
    enum: OperationTypeEnum,
    type: 'enum',
  })
  operation_type: OperationTypeEnum;

  /**
   * SHA-256 hash of the request payload
   * Used to detect if same key is being reused with different payload
   * If hashes don't match → reject request
   */
  @Column({
    type: 'varchar',
    length: 64,
  })
  request_hash: string;

  /**
   * Full request payload (for debugging and audit)
   * Stored as JSONB for flexible querying
   */
  @Column({
    type: 'jsonb',
    nullable: true,
  })
  request_payload: Record<string, any> | null;

  /**
   * Cached response from initial execution
   * Returned to client if operation already succeeded
   * Null while processing or if failed
   */
  @Column({
    type: 'jsonb',
    nullable: true,
  })
  response_snapshot: Record<string, any> | null;

  /**
   * Current status of this operation
   * - PROCESSING: Operation currently in flight
   * - SUCCESS: Operation completed successfully
   * - FAILED: Operation failed (won't retry)
   */
  @Column({
    enum: IdempotencyStatusEnum,
    type: 'enum',
    default: IdempotencyStatusEnum.PROCESSING,
  })
  status: IdempotencyStatusEnum;

  /**
   * Error message if operation failed
   * Used for user-facing error messages
   */
  @Column({
    type: 'text',
    nullable: true,
  })
  error_message: string | null;

  /**
   * Timestamp when this key expires and can be cleaned up
   * Default: 24 hours from creation
   * Configurable per operation type
   */
  @Column({
    type: 'timestamp',
  })
  expires_at: Date;

  /**
   * Timestamp when record was created
   */
  @CreateDateColumn()
  created_at: Date;

  /**
   * Timestamp of last update (status change, retry, etc.)
   */
  @Column({
    type: 'timestamp',
    default: () => 'CURRENT_TIMESTAMP',
    onUpdate: 'CURRENT_TIMESTAMP',
  })
  updated_at: Date;

  /**
   * Helpful constructor
   */
  constructor(partial?: Partial<IdempotencyKey>) {
    Object.assign(this, partial);
  }
}
